run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - whitespace
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - forbidigo
    - gocritic
    - godot
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - grouper
    - nolintlint
    - prealloc
    - revive
    - stylecheck
    - tagliatelle
    - wsl

issues:
  exclude-dirs:
    - node_modules
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
        - gocritic
  max-same-issues: 10
